/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import trabmodelagem1.Main;
import trabmodelagem1.Quarto;
import java.util.ArrayList;
import trabmodelagem1.Atendente;          /* diretiva */

/**
 *
 * @author Miih Rantre
 */
public class TelaQuartos extends javax.swing.JFrame {

    /**
     * Creates new form TelaQuartos
     */
    public String[] nomes = new String[12]; 
    public TelaQuartos() {
        defineString();
        initComponents();  
       
        
    }

    void defineString (){
        String aux="Livre";
  
        for (int i=0; i<12 ;i++){
            if (!(Main.listaQuartos.get(i).nomePaciente().equals("0")))
                nomes[i]=Main.listaQuartos.get(i).nomePaciente();
           else 
                nomes[i]=aux;
            
            //System.out.println ("  "+this.nomes[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(101), nomes[0]},
                { new Integer(102), nomes[1]},
                { new Integer(103), nomes[2]},
                { new Integer(104), nomes[3]},
                { new Integer(201), nomes[4]},
                { new Integer(202), nomes[5]},
                { new Integer(203), nomes[6]},
                { new Integer(204), nomes[7]},
                { new Integer(301), nomes[8]},
                { new Integer(302), nomes[9]},
                { new Integer(303), nomes[10]},
                { new Integer(304), nomes[11]}
            },
            new String [] {
                "Quarto", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setValueAt(nomes[0], 0, 1);
        jTable1.setValueAt(nomes[1], 1, 1);
        jTable1.setValueAt(nomes[2], 2, 1);
        jTable1.setValueAt(nomes[3], 3, 1);
        jTable1.setValueAt(nomes[4], 4, 1);
        jTable1.setValueAt(nomes[5], 5, 1);
        jTable1.setValueAt(nomes[6], 6, 1);
        jTable1.setValueAt(nomes[7], 7, 1);
        jTable1.setValueAt(nomes[8], 8, 1);
        jTable1.setValueAt(nomes[9], 9, 1);
        jTable1.setValueAt(nomes[10], 10, 1);
        jTable1.setValueAt(nomes[11], 11, 1);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 340, 300);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Quartos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 20);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(261, 20, 100, 32);

        setSize(new java.awt.Dimension(416, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed

        
        this.dispose();

    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuartos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
